export enum ApiErrors{
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    REQUEST_SCHEMA_ERROR = 'REQUEST_SCHEMA_ERROR',
    INCORRECT_LOGIN = 'INCORRECT_LOGIN',
    USER_NO_EXISTS = 'USER_NO_EXISTS',
    USER_EXISTS = 'USER_EXISTS',
    FORBIDDEN = 'FORBIDDEN',
    FORBIDDEN_ITEM = 'FORBIDDEN_ITEM',
    INVALID_EMAIL = 'INVALID_EMAIL',
    INVALID_PASSWORD = 'INVALID_PASSWORD',
    ITEM_NO_EXISTS = 'ITEM_NO_EXISTS'
}